Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/miros-i386"
    config.vm.box_version = "0.0.1"

    # Prepare for vagrant package
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true

    config.vm.provision "file", source: "cmake-3.9.0.tar.gz", destination: "/tmp/cmake-3.9.0.tar.gz"
    config.vm.provision "file", source: "core.c.patch", destination: "/tmp/core.c.patch"
    config.vm.provision "file", source: "fs.c.patch", destination: "/tmp/fs.c.patch"
    config.vm.provision "file", source: "getaddrinfo.c.patch", destination: "/tmp/getaddrinfo.c.patch"
    config.vm.provision "file", source: "getnameinfo.c.patch", destination: "/tmp/getnameinfo.c.patch"
    config.vm.provision "file", source: "signal.c.patch", destination: "/tmp/signal.c.patch"
    config.vm.provision "file", source: "stream.c.patch", destination: "/tmp/stream.c.patch"
    config.vm.provision "file", source: "thread.c.patch", destination: "/tmp/thread.c.patch"
    config.vm.provision "file", source: "threadpool.c.patch", destination: "/tmp/threadpool.c.patch"
    config.vm.provision "file", source: "udp.c.patch", destination: "/tmp/udp.c.patch"
    config.vm.provision "file", source: "CMakeLists.txt.patch", destination: "/tmp/CMakeLists.txt.patch"
    config.vm.provision "file", source: "mirbsd.c", destination: "/tmp/mirbsd.c"
    config.vm.provision "shell", path: "bootstrap", privileged: false
end
