Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/miros-i386"
    config.vm.box_version = "0.0.1"

    # Prepare for vagrant package
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true

    config.vm.provision "file", source: "cmake-3.9.0.tar.gz", destination: "/tmp/cmake-3.9.0.tar.gz"
    config.vm.provision "file", source: "core.c.patch", destination: "/tmp/core.c.patch"
    config.vm.provision "file", source: "fs.c.patch", destination: "/tmp/fs.c.patch"
    config.vm.provision "shell", path: "bootstrap.sh"
end
